name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, windows-2025, ubuntu-24.04 ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        pip install build twine

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.9.1'

    - name: Copy Qt
      run: |
        cp -rv ${QT_ROOT_DIR} ./src/qt_dev

    - name: Build
      env:
        AMULET_SKIP_COMPILE: 1
      run: |
        python -m build .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_QT_DEV_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
